# https://www.youtube.com/watch?v=DSjVHqdbkBw&ab_channel=%E5%BD%AD%E5%BD%AD%E7%9A%84%E8%AA%B2%E7%A8%8B
# 抓取原始碼
import json
import urllib.request as req

url = "https://www.youtube.com/youtubei/v1/player?key=AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8&prettyPrint=false"
requestData = {{"context": {"client": {"hl": "zh-TW", "gl": "TW", "remoteHost": "2001:b011:b808:9e6f:49a6:9d8d:cf4a:7b26", "deviceMake": "", "deviceModel": "", "visitorData": "CgtWcG8wdXUtdk5GYyiQ-c2fBg%3D%3D", "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36,gzip(gfe)", "clientName": "WEB", "clientVersion": "2.20230217.01.00", "osName": "Windows", "osVersion": "10.0", "originalUrl": "https://www.youtube.com/watch?v=jHRqY_osUVo&pp=YAHIAQE%3D", "screenPixelDensity": 1, "platform": "DESKTOP", "clientFormFactor": "UNKNOWN_FORM_FACTOR", "configInfo": {"appInstallData": "CJD5zZ8GEIfdrgUQvbauBRCi7K4FENrprgUQuNSuBRDloP4SEJT4rgUQgt2uBRDn964FEInorgUQzPWuBRD-7q4FELiLrgUQtpz-EhDi1K4FELCk_hIQzN-uBRCKg68FEJCq_hIQkfj8Eg%3D%3D"}, "screenDensityFloat": 1.25, "timeZone": "Etc/GMT-8", "browserName": "Chrome", "browserVersion": "109.0.0.0", "acceptHeader": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9", "deviceExperimentId": "ChxOekl3TWpBME1ERTRPVGs0TnpFek5qUTROQT09EJD5zZ8GGOWSy58G", "screenWidthPoints": 982, "screenHeightPoints": 746, "utcOffsetMinutes": 480, "userInterfaceTheme": "USER_INTERFACE_THEME_LIGHT", "memoryTotalKbytes": "8000000", "clientScreen": "WATCH", "mainAppWebInfo": {"graftUrl": "/watch?v=jHRqY_osUVo&pp=YAHIAQE%3D", "pwaInstallabilityStatus": "PWA_INSTALLABILITY_STATUS_CAN_BE_INSTALLED", "webDisplayMode": "WEB_DISPLAY_MODE_BROWSER", "isWebNativeShareAvailable": true}}, "user": {
    "lockedSafetyMode": false}, "request": {"useSsl": true, "internalExperimentFlags": [], "consistencyTokenJars": []}, "clickTracking": {"clickTrackingParams": "CL4DENwwIhMI0P3B-6Ck_QIVFaZWAR0BCgjJMgpnLWhpZ2gtcmVjWg9GRXdoYXRfdG9fd2F0Y2iaAQYQjh4YngE="}, "adSignalsInfo": {"params": [{"key": "dt", "value": "1676901520710"}, {"key": "flash", "value": "0"}, {"key": "frm", "value": "0"}, {"key": "u_tz", "value": "480"}, {"key": "u_his", "value": "4"}, {"key": "u_h", "value": "864"}, {"key": "u_w", "value": "1536"}, {"key": "u_ah", "value": "816"}, {"key": "u_aw", "value": "1536"}, {"key": "u_cd", "value": "24"}, {"key": "bc", "value": "31"}, {"key": "bih", "value": "746"}, {"key": "biw", "value": "966"}, {"key": "brdim", "value": "0,0,0,0,1536,0,1536,816,982,746"}, {"key": "vis", "value": "1"}, {"key": "wgl", "value": "true"}, {"key": "ca_type", "value": "image"}], "bid": "ANyPxKojG-5oa_QHECvnsThuHyBP1okc2eY8hBEFAZttTLK1LBMiM0EA8CeVUm1U6VQf_yGM_rQDgfq0TUhSP2y2thldOeuWwg"}}, "videoId": "jHRqY_osUVo", "params": "YAHIAQE%3D", "playbackContext": {"contentPlaybackContext": {"currentUrl": "/watch?v=jHRqY_osUVo&pp=YAHIAQE%3D", "vis": 5, "splay": false, "autoCaptionsDefaultOn": false, "autonavState": "STATE_NONE", "html5Preference": "HTML5_PREF_WANTS", "signatureTimestamp": 19404, "autoplay": true, "autonav": true, "referer": "https://www.youtube.com/", "lactMilliseconds": "-1", "watchAmbientModeContext": {"watchAmbientModeEnabled": true}}}, "racyCheckOk": false, "contentCheckOk": false}}
request = req.Request(url, headers={
    "cookie": "PREF=f4=4000000&tz=Etc.GMT-8; VISITOR_INFO1_LIVE=Vpo0uu-vNFc; DEVICE_INFO=ChxOekl3TWpBME1ERTRPVGs0TnpFek5qUTROQT09EOWSy58GGOWSy58G; SID=TwjQqI-1DnXIOOnFfrIZPaW3Ob4WBC7lYaPdYlHHtxFWDLovIfWFPuNk1kuuZ0GzO4b9Sw.; __Secure-1PSID=TwjQqI-1DnXIOOnFfrIZPaW3Ob4WBC7lYaPdYlHHtxFWDLov16e_3enIDW7Rg1X_MHM5uA.; __Secure-3PSID=TwjQqI-1DnXIOOnFfrIZPaW3Ob4WBC7lYaPdYlHHtxFWDLovBCTxvdd7omLNN-XYMDp5VQ.; HSID=AlheS9wMCIXythyvH; SSID=A8Wxjt9MWOFrCs6bi; APISID=MVbCVjX1dlCkNJxO/ARFfTwxeBdWZ8brgJ; SAPISID=WdTACYoDbq-YGNNi/AeapxhtpwwgfOT-9X; __Secure-1PAPISID=WdTACYoDbq-YGNNi/AeapxhtpwwgfOT-9X; __Secure-3PAPISID=WdTACYoDbq-YGNNi/AeapxhtpwwgfOT-9X; LOGIN_INFO=AFmmF2swRgIhAOC7HHJlvs035xGS9cAOBHqurQmiQpoY6lFRO2g5LXPxAiEAvCKOfXS-A45rKiyA2wfwnIOmNgOOsJyAhh0UhX2cKmM:QUQ3MjNmenlDWnV5YlFTTlIyeGpnNkd0alhxeHZaamRFZ25yWGxJQ2NIMktYb3VtRk9pOWsyX2NObmdEUW5GMTlESkd4VVRrcDVzRHFVOEgtWGE5eVF3Y2x6d1l5bjVfa2YzTTZSOWw3VFZBdG9nWjFWaDdlWUliNUNwdGg1eEZxQnhpaGwySW9hNWVyd3laRHBySVFKSFFIWWJvY01zRGxR; YSC=wohNSlEyjm4; SIDCC=AFvIBn8AASTe8-W2fh_10oGC5XDnwFk5CGbBb2K19nATMV45NrTcJn825FJtNN_aafaCjYN5Wg; __Secure-1PSIDCC=AFvIBn9CXzKrJcEmUr0mpuSRUe-zaO6Kbh3TAsjzkVoRAAqmVTnhR712HgNnI83MmtpQ_pXFsyU; __Secure-3PSIDCC=AFvIBn_Z_oOkWwVb6aNlnUNMWEI33AJIogS3vBg8R-Dw5um1BYTb3VrKQtrNyv-03nlT3fi8HQ",
    "content-type": "application/json",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
}, data=json.dumps(requestData).encode("utf-8"))
with req.urlopen(request) as response:
    result = response.read().decode("utf-8")

    # 解析原始碼
print(result)
